export const ChatActionTypes = {
  ON_CLEAR_MESSAGES: "ON_CLEAR_MESSAGES",
  ON_CONNECT_SOCKET: "ON_CONNECT_SOCKET",
  ON_GET_MESSAGE: "ON_GET_MESSAGE",
  ON_GET_ROOMS_LIST: "ON_GET_ROOMS_LIST",
  ON_JOIN_ROOM: "ON_JOIN_ROOM",
  ON_LEAVE_ROOM: "ON_LEAVE_ROOM",
  ON_MESSAGE_RECIEVED: "ON_MESSAGE_RECIEVED",
  ON_SEND_MESSAGE: "ON_SEND_MESSAGE",
  ON_SET_PREVIOUS_MESSAGES: "ON_SET_PREVIOUS_MESSAGES",
  ON_SET_ROOM_USERS: "ON_SET_ROOM_USERS",
  ON_SET_ROOMS: "ON_SET_ROOMS",
  ON_USER_JOINED: "ON_USER_JOINED",
};
