export const ChatActionTypes = {
  ON_JOIN_ROOM: "ON_JOIN_ROOM",
  ON_LEAVE_ROOM: "ON_LEAVE_ROOM",
  ON_CREATE_ROOM: "ON_CREATE_ROOM",
  ON_SEND_MESSAGE: "ON_SEND_MESSAGE",
  ON_GET_ROOMS_LIST: "ON_GET_ROOMS_LIST",
  ON_GET_PREVIOUS_MESSAGES: "ON_GET_PREVIOUS_MESSAGES",
  ON_GET_MESSAGE: "ON_GET_MESSAGE",
  ON_CREATE_SOCKET: "ON_CREATE_SOCKET",
  ON_MESSAGE_RECIEVED: "ON_MESSAGE_RECIEVED",
  ON_CLEAR_MESSAGES: "ON_CLEAR_MESSAGES",
  ON_SET_USERS_IN_ROOM:"ON_SET_USERS_IN_ROOM"
};
