export const ManageActionTypes = {
  ON_FETCH_START: "ON_FETCH_START",
  ON_FETCH_FAILED: "ON_FETCH_FAILED",
  ON_QUERY_USERS_SUCCESS: "ON_QUERY_USERS_SUCCESS",
  ON_GET_USER_SUCCESS: "ON_GET_USER_SUCCESS",
  ON_CLEAR_USERS: "ON_CLEAR_USERS",
};
